### ISSUE TITLE
Update IP and MAC tables on administrator->internet site

### ISSUE THREAD

**Issue by sszajbely** [EotvosCollegium/mars#115]
These tables are updated according to the last radius and dhcp configs. Since we updated these these tables aren't updating at all.

**Comment by kdmnk** [comment]
What do we need here exactly?

**Comment by sszajbely** [comment]
If we don't want to search in the logs by hand, we could get the user logging in (with their wifi username and MAC address) from the radius log and their IP at the time from the dhcp leases file using the MAC address acquired from the radius log

**Comment by sszajbely** [comment]
So the radius log file is located at `/var/log/freeradius/radius.log`, the leases file at `/var/lib/dhcp/dhcpd.leases`. Both can be read without sudo. So we just need to write a script getting the mac address from the radius log, linking it with the user, storing it in the database, then opening the leases file and searching for the IP address using the MAC.

Last time we agreed, that the MAC address should be sufficient, as IIG will likely tell us the MAC not just the IP.

I also think, that we should come back to this issue after #158 is ready, otherwise there will be a lot of unnecessary work with it.
