### ISSUE TITLE
Revisit input handling for dates

### ISSUE THREAD

**Issue by kdmnk** [EotvosCollegium/mars#12]
The materialize one does not have a good UX.

Use the one from the router page everywhere (mostly at registration). Alternatively, create 3 input fields for year/month/date. Also, it would be nice to include this as an <x.input component.

**Comment by sszajbely** [comment]
What is the problem with the materialize date picker?

**Comment by kdmnk** [comment]
You can not go more than x years back if you do not close it halfway, which is confusing.
