### ISSUE TITLE
Fix community service policy

### ISSUE THREAD

**Issue by kdmnk** [EotvosCollegium/mars#133]
I should not be able to access the (empty) page when I do not have permission to see the community services.
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/56202545/193056873-049cf4b9-fd04-481b-bcd3-754e5868db64.png">

Also, add the sys-admins to see the cs-s.

**Comment by sszajbely** [comment]
Well you could have past community services you would want to see. I guess I could make it so that you are able to see it only if you can create one OR you have past ones. Is it okay like that?

**Comment by sszajbely** [comment]
So you have permission to see the community services, that's why you can open the page. It just happens to be that you don't have any :D

**Comment by kdmnk** [comment]
Okay, I suppose I could not create a new one, because I am not active. And the list is empty... :D 
Use @forelse and show an "empty" message then.
