### ISSUE TITLE
Fix status certificates

### ISSUE THREAD

**Issue by kdmnk** [EotvosCollegium/mars#14]
See https://github.com/luksan47/mars/issues/603 (done) and https://github.com/luksan47/mars/issues/448

**Comment by kdmnk** [comment]
Do we have a new document format for this?

**Comment by kdmnk** [comment]
@horcsinbalint do we have anything else to do here?

**Comment by horcsinbalint** [comment]
I don't know what this issue was about and whether it is still relevant. (I have not added the status to the cert as far as I can remember.)
