### ISSUE TITLE
Change semester dates

### ISSUE THREAD

**Issue by sszajbely** [EotvosCollegium/mars#144]
The beginning and end of the semesters is not defined well, ex. the spring semester ends in July, but the autumn semester starts in September. This creates a two month gap where noone is active.

The Semester::current() function is ambiguous at best.

We should take a look at these as the model gets more and more important with the activation of the users.

**Comment by kdmnk** [comment]
You are right, but I don’t think that will cause any problem. In the summer, everyone residing in the building are considered a tenant.

**Comment by sszajbely** [comment]
But then someone has to give them the tenant role. Which will not happen

**Comment by kdmnk** [comment]
And what happens if they do not have a tenant role in the summer? Which users will have a problem then?

**Comment by sszajbely** [comment]
Well they will be redirected to the semester activation page. Which I find odd, because the semester only begins in September.

**Comment by kdmnk** [comment]
I proposed a solution in your pr. Otherwise, let it be for now.

**Comment by kdmnk** [comment]
I plan to make some tests at least for the semesters.

**Comment by sszajbely** [comment]
It's not that the tenants will be redirected, but the collegists will be redirected to the semester activation page.

**Comment by sszajbely** [comment]
I want to modify the end of the spring semester to august, and update the Semester::current() accordingly.

This way there won't be any "missing months" in-between semesters and we would eliminate any problems caused by this.

**Comment by kdmnk** [comment]
Okay, but will it be working with https://github.com/EotvosCollegium/mars/issues/99?

**Comment by sszajbely** [comment]
Well I think I'll create a new EventTrigger, and the activation dates of those are totally independent of the semesters.

**Comment by kdmnk** [comment]
Also change semesters table to add composite key for (year,part)

**Comment by kdmnk** [comment]
The semesters seem to work the way we have now. We have tests and the gaps are defined explicitly so that always the next semester is returned. Having more exact start and end dates seems more beneficial while we do not have any specific logic connected to the gaps between semesters.

**Comment by kdmnk** [comment]
> Also change semesters table to add composite key for (year,part)

Done in #302
