### ISSUE TITLE
Fix dark mode issues

### ISSUE THREAD

**Issue by ejcroot** [EotvosCollegium/mars#149]
Hello! Sötét mód kompatibilitási problémák lennének - szobabeosztás popup nem olvasható, mert fehér háttér, fehér betűk, valamint a bal oldali sáv kinyitható mappái is hasonló problémával küzdenek, hover over halványan, szürkével látszik, de az nélkül emlékezetből megyek az oldalakra.

> This bug is reported by Šiška Dávid and generated automatically.

**Comment by sszajbely** [comment]
I wanted to take a look at this

**Comment by kdmnk** [comment]
Yeah we have an other issue for this
