### ISSUE TITLE
Fix selecting users by status

### ISSUE THREAD

**Issue by viktorcsimma** [EotvosCollegium/mars#151]
On the Users page, when I select a status, by default "Active" remains checked and it finds no one (it searches for people with more than one statuses). Maybe we should make these behave like radio buttons. Or can a user have more than one statuses?

![Bildschirmfoto von 2022-10-11 12-27-36](https://user-images.githubusercontent.com/70488334/195066870-4684cc39-a209-4965-9326-62d789fc5758.png)

**Comment by kdmnk** [comment]
Good point. For that, we just need to modify the addStatus in the livewire (https://github.com/EotvosCollegium/mars/blob/development/app/Http/Livewire/ListUsers.php#L78) to overwrite the previous one. (Possibly remove the list representation as well).
@viktorcsimma would you like to do that?

**Comment by kdmnk** [comment]
The other solution would be to filter the users having any of the given statuses (instead of having all). Probably makes more sense.

**Comment by viktorcsimma** [comment]
That’s a good idea; thank you:) I think I’ll try it this weekend.
