### ISSUE TITLE
Adding anonymous vote system

### ISSUE THREAD

**Issue by viktorcsimma** [EotvosCollegium/mars#195]
Until the next General Assembly, I would like to add a feature through which people could vote using their Urán account. I already have a plan for the database which would not contain who voted for what; if you have any comments, I would appreciate them:)

![Bildschirmfoto von 2023-01-17 18-36-00](https://user-images.githubusercontent.com/70488334/212972416-0864b100-227d-476c-acbe-c2f3a855a38f.png)

**Comment by kdmnk** [comment]
Yes, I thought about this also. Good initative. To make it simpler, I don't think we need to keep track of the sittings (this can be useful anyway), and you don't need time_of_voting as the default created_at field does the same. Also question_id and id. And I'd rename the options table to question_options to be more readable.  @viktorcsimma

**Comment by viktorcsimma** [comment]
These are good ideas; thank you:) I already have a UI for the sittings, so I think they can stay now, but I'll apply the others.
