### ISSUE TITLE
Non-collegists(?) locked out at beginning of new semester

### ISSUE THREAD

**Issue by viktorcsimma** [EotvosCollegium/mars#201]
Now that the new semester has begun in Urán, Ádám was locked out: he was redirected to secretariat/status-update to update his status, but there he got a 403 error (maybe as he was not a collegist).

As a quick fix, I commented out the redirecting section in `app/Http/Middleware/PossibleRedirects.php`. But here, I see that it should check whether the user is a collegist or not... Maybe people who were collegists in earlier years are treated as collegist in `User::isCollegist()`.

I'd be grateful if you have any ideas;)

**Comment by sszajbely** [comment]
I think I know the problem, but you'll have to check. Ádám has the collegist role and `isCollecist()` definitely works. But there is a check on the status page if the last status of the user was deactivated, then he gets a 403 error. This is only a measure to prevent already deactivated members from reactivating their own status. But there is no check like this in the middleware.

So the easy fix is to check if the last semester of the user was deactivated, and if so don't redirect.
