### ISSUE TITLE
Add studied programme to status update form.

### ISSUE THREAD

**Issue by sszajbely** [EotvosCollegium/mars#204]
This way the website of the workshops could be updated more easily.

Remark: this is a feature request from Ákos Blaskovics.

**Comment by kdmnk** [comment]
What course do you mean exactly?

**Comment by sszajbely** [comment]
Egyetemi szak, csak nem tudok angolul :D

**Comment by kdmnk** [comment]
We have it now in educationalInformation for the new students. It might be a good idea to show the users every personal/educational data for review regularly.
