### ISSUE TITLE
Finalise ALFONSO status handling and language exam uploads

### ISSUE THREAD

**Issue by ejcroot** [EotvosCollegium/mars#228]
Az előző két issue-ból legyen kiszámolva egy olyan rovat, hogy &quot;ALFONSÓ-kötelezettség: fennáll / teljesítve / (eleve) nem áll fönn&quot;. Ezt a nyelvi munkaközösség-vezető (nymk-vezető) állítgathassa. Mesteresként fölvettnél automatikusan a &quot;nem áll fönn&quot; jelenjen meg. Különben pedig legyen kiszámolva, hogy hány féléve van még hátra, túllépte-e (NB: OT-nél 8 félév áll rendelkezésre).

> This bug is reported by Blaskovics Ákos and generated automatically.

**Comment by kdmnk** [comment]
See also https://github.com/EotvosCollegium/mars/issues/230 and https://github.com/EotvosCollegium/mars/issues/231
