### ISSUE TITLE
Select inits are loaded multiple times

### ISSUE THREAD

**Issue by kdmnk** [EotvosCollegium/mars#23]
See https://github.com/luksan47/mars/issues/580

**Comment by kdmnk** [comment]
@luksan47 looks like they thought about this also :) See https://laravel.com/docs/8.x/blade#the-once-directive.
But I think we need further optimisation on the sql queries also.

**Comment by luksan47** [comment]
If I remember correctly, we already solved this with `once`. Maybe it was missing for selects?
