### ISSUE TITLE
Ask for ALFONSO language initially

### ISSUE THREAD

**Issue by ejcroot** [EotvosCollegium/mars#232]
A nem mesteresként fölvettektől az első státuszállításkor kérdezze meg a rendszer, hogy melyik ALFONSÓ-nyelvet választják. Az volna a jó, ha ezt tudnák módosítani egy megadott határidőig, nem úgy, mint a státuszt. Szóval lehet, érdemes különszedni mégis a státuszállítástól.

> This bug is reported by Blaskovics Ákos and generated automatically.

**Comment by kdmnk** [comment]
We already ask this at registration.
