### ISSUE TITLE
Extend and finalise status form after the semester ends

### ISSUE THREAD

**Issue by kdmnk** [EotvosCollegium/mars#238]
- Confirm every existing educational and personal data
- Confirm alfonso status, upload language exams (see #228 )
- Confirm general assembly attendance (see #239 )
- Ask for registered EC courses
- Ask for possible academic results
- Ask for public activities, confirm/upload the ones under the student council
- Anything else...?

Store the data and extend the user table export.

**Comment by kosblskvcs** [comment]
- Ask for average grade in the current semester
- Ask for average grade in the previous semester (it may not be necessary if the data from the previous form can be stored)
- registered EC courses: it would be great if title and Neptun code of the course could be filled in separately, but would be related to each other (even better: chosen from a list, thus the code automatically appearing)
- Academic results and public activities in detail:

> - Szakmai eredmények (szöveges)
> - Kutatómunka (rövid leírás, témavezető/kutatócsoport)
> - Publikációk (nemzetközi/hazai)
> - Konferenciarészvétel (TDK/OTDK, nemzetközi/hazai konferencián előadás/poszter)
> - Ösztöndíjak, elismerések
> - Oktatási tevékenység (egyetemen vagy Collegiumban)
> - Egyéb tanulmányi vagy szakmai eredmény/tevékenység

> - Közéleti tevékenységek (szöveges)
> - Collegiumhoz kötődő rendezvényszervezés (rendezvény, feladatkör)
> - Választmányi munkában való részvétel (tisztségviselő, bizottsági tag, műhelytitkár)
> - Egyéb (Collegiumhoz kötődő) közéleti tevékenység
> - Egyéb közéleti tevékenység

**Comment by kdmnk** [comment]
... and #188 ?
