### ISSUE TITLE
ALFONSÓ refinements

### ISSUE THREAD

**Issue by kosblskvcs** [EotvosCollegium/mars#285]
A mesteresként fölvetteknek (felvétel évéből + képzési adatok összevetéséből látszik) eleve nincs kötelezettségük. Senioroknak szintén nincs.
OT-soknak legyen +1 évük B2 és C1 esetén is.

**Comment by viktorcsimma** [comment]
Well... the problem is that we cannot reliably determine whether a teacher has a language faculty (see [2. § (3) a](https://eotvos.elte.hu/media/c2/f9/694cb0adfdacfcf1f4cbf258073b340866456ed7c239c4d250acf71f43b3/ec_alfonso_nyelvi_program.pdf)). But I can check the other two cases.
