### ISSUE TITLE
Disable form submit buttons after first submission

### ISSUE THREAD

**Issue by kdmnk** [EotvosCollegium/mars#296]
...to avoid having the forms sent multiple times.
Especially when we send emails in the background.
Try to come up with a general solution.

**Comment by matteobandoni** [comment]
you could use a boolean variable that indicates whether or not to do the submit.

```
var can_submit = true;

$('.button').on('click', function(event){
    event.preventDefault();
    if(can_submit){
         can_submit = false;
         //insert your code
    }
})
