### ISSUE TITLE
Wrong status shown at some applications

### ISSUE THREAD

**Issue by viktorcsimma** [EotvosCollegium/mars#319]
@AdamSulan and I have taken a look at them and it seems that if someone reapplies with an already-existing account with `Extern` status to a `Resident` status _and_ they have not finalised their application yet, the application tile often shows `Extern` instead of `Resident`. The problem does not seem to persist for users with a new account, or if they have already finalized their application. However, even for some pending applications it is shown correctly.

**Comment by BertalanD** [comment]
Fixed by #560

Whether a user applies for resident status is now a property of `Application`, unrelated to the user's Collegist role.
