### ISSUE TITLE
Alumni cannot apply for collegist

### ISSUE THREAD

**Issue by viktorcsimma** [EotvosCollegium/mars#320]
Again discovered by @AdamSulan. After following the [link](uran.eotvos.elte.hu/application), the site redirects them to the _"tell me when you are going to move"_-screen, and to the home page after saving that. If they try again, the same happens.

**Comment by kdmnk** [comment]
They should see an apply as a collegist button on the bottom of that page. Can not you see that @viktorcsimma @AdamSulan ?

**Comment by viktorcsimma** [comment]
It looks like this:
![DC9B87DC-D59D-40E0-9BDF-14C87C4E81F0](https://github.com/EotvosCollegium/mars/assets/70488334/a3e87f04-02e6-4cc1-ba6c-bbf30f660150)

**Comment by kdmnk** [comment]
I checked. It should only happen with Adam because he is already an alumni... I'll fix it
