### ISSUE TITLE
Error when saving educational data – 'resident' role missing?

### ISSUE THREAD

**Issue by viktorcsimma** [EotvosCollegium/mars#324]
I've received an error report from someone who wants to reapply for resident status, but cannot change his educational data – he just gets a 500 when trying to save. I've checked it out and it seems that the `resident` role is missing from the table `roles`.

From Role.php:169:

```php
    public function getObject(int|string|Workshop|RoleObject $object = null): Workshop|RoleObject|null
    {
        if ($object instanceof Workshop) {
            return $object;
        }
        if ($object instanceof RoleObject) {
            return $object;
        }
        return Cache::remember('role_'.$this->id.'_object_'.$object, 86400, function () use ($object) {
            /* @var RoleObject|Workshop|null $object */
            if ($this->has_objects && is_numeric($object)) {
                $object = $this->objects()->find((int)$object);
            } elseif ($this->has_objects) {
                $object = $this->objects()->firstWhere('name', $object);
            } elseif ($this->has_workshops && is_numeric($object)) {
                $object = Workshop::find((int)$object);
            } elseif ($this->has_workshops) {
                $object = Workshop::firstWhere('name', $object);
            } elseif (!isset($object)) {
                $object = null;
            }
            //throw new \Exception($object);
            if (!$this->isValid($object)) {
                throw new InvalidArgumentException("Role object/workshop '".$object."' does not exist for the " . $this->name . " role.");
            }
            return $object;
        });
    }
```

Here, `isValid` expects a `Role` object, but gets a string. When I comment out the row throwing that test exception, it seems that `$object` is the string `'resident'`. And it doesn't exist in the database.

What should we do here? I wasn't sure whether I should simply add it to the database; that's why I'm asking for your help. Thanks in advance:)

**Comment by kdmnk** [comment]
Resident is a RoleObject connected to the collegist Role. So it is in a different table, it should be fine. 

I'll take a look. Next time, just try to paste the error log from the server. ;)

**Comment by kdmnk** [comment]
I think its just this: `Integrity constraint violation: 1062 Duplicate entry 'xxxx@student.elte.hu' for key 'educational_information.educational_information_email_unique'`

I'll close this one.
