### ISSUE TITLE
„NoApplications” role

### ISSUE THREAD

**Issue by viktorcsimma** [EotvosCollegium/mars#325]
Maybe we could create a new role which makes a user unable to see applications. I don’t know how much sense this would make (especially for admins), but if we trust them, we could prevent accidental checks. And for workshop secretaries, this could be quite useful. What do you think?

**Comment by kdmnk** [comment]
I don't understand what's the point in this

**Comment by viktorcsimma** [comment]
This way, we don’t have to take away their usual roles from them. So secretaries could do their secretary-things, without seeing applicants. But for now, it’s simpler to temporarily revoke their roles.

**Comment by horcsinbalint** [comment]
For applicants who have been admitted we might need to store their application data for more than 80 years, so their should be a way to archive them. (I would not want to translate this: NFTV 3. melléklet I/B. 3.: "Az adatkezelés időtartama: a hallgatói jogviszony megszűnésére vonatkozó bejelentéstől számított nyolcvan évig.")
