### ISSUE TITLE
Issues with current application system

### ISSUE THREAD

**Issue by kdmnk** [EotvosCollegium/mars#332]
- [x] Finalise: users do not get deleted
- [x] https://github.com/EotvosCollegium/mars/issues/312
- [x] #489
- [x] Correct the anternet access date for admitted collegists
- [x] #327
- [ ] come up some solution for this: https://github.com/EotvosCollegium/mars/issues/325
- [x] #321
- [x] Connect the applications to semesters through the PeriodicEvent

**Comment by viktorcsimma** [comment]
Could you explain the internet access date problem a bit more? Maybe even in a separate issue, if you have the time.

Also, for the first point: this means that after clicking the finalise button, they stay in the database, right?

**Comment by horcsinbalint** [comment]
We might need to store data of accepted applications for more than 80 years. We should probably be able to archive this data easily. (NFTV 3. melléklet I/B. 3. "Az adatkezelés időtartama: a hallgatói jogviszony megszűnésére vonatkozó bejelentéstől számított nyolcvan évig.")
@kosblskvcs

**Comment by kdmnk** [comment]
@horcsinbalint @viktorcsimma If we can merge #560 #572 and #574 we should be ready for final tests and opening the admission period. Make sure that you delete the applications from the last year beforehand (that was a bug).
I will implement #327 and the finalise method again in the meantime, those are less of a priority.

**Comment by horcsinbalint** [comment]
So we need to truncate table `application_forms`?

**Comment by kdmnk** [comment]
I did not see any data now from last year, but yes.

**Comment by horcsinbalint** [comment]
There are some records in the DB.
![image](https://github.com/user-attachments/assets/b680b231-979a-418c-85ef-4b4ccf2fa005)

I have lost the track of these PR's, and will not be able to test them as I am busy with unrelated stuff - mostly TermTudTábor - (I am not planning on commenting on this repo for the next 10 days), but I am a bit concerned whether there is enough time to test all these as the application will be opened on Wednesday and the Student Council is also quite busy.
