### ISSUE TITLE
Set free printing true by default

### ISSUE THREAD

**Issue by kosblskvcs** [EotvosCollegium/mars#344]
Fwd: "Meg lehetne oldani azt esetleg, hogy akinek van ingyen nyomtatása, annak ne kelljen beállítgatni az ingyen oldalak nyomtatását, hanem automatikusan abból vonja le neki az oldalakat?"

**Comment by kdmnk** [comment]
I think this can be achieved easily by setting the free pages checkbox to true by default. 

However, in principle, free printing should not be used for personal documents. What's more common for them, to print with free pages or personal printing?  I would not encourage free printing by this feature.

**Comment by kosblskvcs** [comment]
I think it's not that widespread among users to have free printing. The one who asked for it reports that free printing is used considerably more frequently than personal printing. Most of the time, several documents are printed for a single session of a language course and one has to set the checkbox for every document separately.

**Comment by kdmnk** [comment]
Then the best solution would be to store the value in a cookie so the checkbox stays checked within a session.
