### ISSUE TITLE
Assigning resident externs to rooms

### ISSUE THREAD

**Issue by viktorcsimma** [EotvosCollegium/mars#345]
There have been complaints that resident externs cannot be added to rooms, because their status is officially Extern and only residents are allowed.

My first idea is simply to lift this restriction. Another solution is to create a new status for resident externs, but as far as I remember, @machiato32 did not want to formalise it (I don't know if it's still actual). What do you think?

**Comment by kdmnk** [comment]
Just remove the constraints for now
