### ISSUE TITLE
Adding new fields to users' profile (research topic, photo etc.)

### ISSUE THREAD

**Issue by viktorcsimma** [EotvosCollegium/mars#349]
The student council has requested workshop secretaries to provide more information about members. This includes:
- Their research topic.
- How occupied they are.
- A photo of them.
- _(Maybe some other personal data; I will have to ask about that.)_

The secretaries have suggested this could be added to Mars. What do you think?

**Comment by kdmnk** [comment]
We already have photos when they apply to be a collegist, but we do not display them afterwards (maybe we delete them currently). 
"How occupied they are" is that a text field? Who should update it? Who should be able to see it?

**Comment by viktorcsimma** [comment]
I quote the original request:

_Sziasztok! Tegnap a Műhelytitkári Fórumon felmerült a Választmány részéről egy igény arra, hogy röviden információt kérjünk a collegisták leterheltségéről, kutatási témáiról, személyéről, akár egy kis fényképpel egybekötve. A műhelytitkárok felvetették, hogy ez működhetne az Uránban, és akkor kevesebb dokumentumot kellene kezelnünk. Azt szeretném kérdezni, hogy belátható időn belül (1-1,5 hónap) lehetséges lehet-e a profil fül fejlesztése, kiegészítve olyan rubrikákkal, ahol lehet ilyesmiről írni? Köszönöm előre is!_

As I understand, collegists would fill these fields by themselves, and they would be seen by workshop secretaries and student council members. But I’ll ask about it.

Another thing that crossed my mind is whether these fields should be global or tied to the current semester. The latter would make sense (since they are occupied to a different extent in different semesters). I’ll ask about that too (and also about whether this should be a text field or some numeric statistic).

**Comment by viktorcsimma** [comment]
Now I have more information: visibilities are as I have thought, occupiedness would be a simple text field, and it need not necessarily be tied to semesters (it would be advantageous, but that’s not a priority).

**Comment by kdmnk** [comment]
Just be mindful of collegists' requests regarding maintainability, sustainability and given value in general.
We don't want to implement something that would happen to be not practical to use or update in real scenarios, or some years later another change would be requested. 
Consider and agree on who is responsible for updating these fields (if collegists, why would they care?) and what exactly should they consist of before implementing them. 
I'd go for a solution as general as possible. 
The only information sensible to me is the research project to add to the profile, we can then also include them in the end-of-semester report automatically. For the others (Having a field "how occupied they are" is too vague for me), just one big text field that can be filled with whatever will be needed. Be aware though that our GDPR Privacy notice does not currently comprise these personal data.

**Comment by viktorcsimma** [comment]
Ah, that's a nice idea:D I've been thinking about something like a form that can be edited by authorised users; but then I realised Google Forms is simpler for that. The big text field does the work and keeps it simple.

Actually, I'm also a bit sceptic about the usefulness of this feature. But we can give it a try; this way, it isn't too complicated. And we can still remove it if no one uses it.
