### ISSUE TITLE
Multiple issues with routers

### ISSUE THREAD

**Issue by horcsinbalint** [EotvosCollegium/mars#362]
If a router is created without a date of acquisition, the 5G MAC address won't be saved.

A router's data cannot be edited without changing the IP address, because it would complain that the IP address has been already taken.

**Comment by kdmnk** [comment]
> A router's data cannot be edited without changing the IP address, because it would complain that the IP address has been already taken.

Use our custom SameOrUnique rule. Not sure if we support this specific scenario yet though
