### ISSUE TITLE
Caching is not properly supported

### ISSUE THREAD

**Issue by horcsinbalint** [EotvosCollegium/mars#364]
Caching in a production server can be important using Laravel. By running the following code to make caches, there are issues in blades that `{{ENV('EXAMPLE')}}` are not loading on the page.
```
php artisan event:cache
php artisan route:cache
php artisan view:cache
php artisan config:cache
```

**Comment by kdmnk** [comment]
I don't understand. We did not use artisan caching so far.

**Comment by horcsinbalint** [comment]
To improve the security, maintainability and reliability of our systems I'm doing some restructuring of our servers. Since they might come with some performance burden and I would like to meet the recommendations set forth in the Laravel documentation (https://laravel.com/docs/9.x/configuration#configuration-caching, https://laravel.com/docs/9.x/deployment#optimizing-configuration-loading), I would also would like to set up proper caching for used resources.

The changes that were done in the [deployment](https://github.com/EotvosCollegium/mars/tree/deployment) branch seem to be enough to allow proper caching.

I'm planning on making proper branching and PRs for the upstream [development](https://github.com/EotvosCollegium/mars/tree/development) branch, but there were several issues during the migration of the infrastructure and I was not yet able to properly document all of the features that did not work as expected.
