### ISSUE TITLE
Set up CI/CD

### ISSUE THREAD

**Issue by kdmnk** [EotvosCollegium/mars#378]
Use the 'release' or 'deployment' branch for continuous delivery (whenever we push, the server updates automatically)

A proper push flow could be 'feature-related-branch' -> 'development' (-> 'staging') -> 'release'

**Comment by horcsinbalint** [comment]
I have created a cronjob that polls every minute if there have been changes on the `staging` and `deployment` branches, and deploys them if needed. So in practice we have continous deployment. #444 superseeds this issue
