### ISSUE TITLE
Set up test server

### ISSUE THREAD

**Issue by kdmnk** [EotvosCollegium/mars#379]
create a 'staging' branch, with a copy of the real database.

Dependent on #378

**Comment by horcsinbalint** [comment]
Should we put the staging server on the same machine as the deployment server? I think it should work if set up correctly.

**Comment by kdmnk** [comment]
Not the best solution, but it should be possible, especially with docker.


________________________________

**Comment by horcsinbalint** [comment]
Dependent on #395

**Comment by horcsinbalint** [comment]
Test server has been set up, #395 is not fixed yet but the test server is mostly functional
