### ISSUE TITLE
Finalise semester evaluation form

### ISSUE THREAD

**Issue by kdmnk** [EotvosCollegium/mars#399]
- [ ] Send reminder before the deadline
- [ ] Send info to the secretariat and president when the form is started and ended
- [x] PhD students do not need to fill the form.
- [ ] anything else?

**Comment by horcsinbalint** [comment]
How high is the priority? Should it be deployed this semester?

**Comment by kdmnk** [comment]
The only priority is that we will inactivate everyone who haven't fill the form, including phds, so yes, I'll fix it in the next week.

________________________________

**Comment by horcsinbalint** [comment]
Okay, I will try to make deployment and development branches consistent ASAP.
