### ISSUE TITLE
No indication of bug reports being exposed publicly

### ISSUE THREAD

**Issue by horcsinbalint** [EotvosCollegium/mars#425]
If a user submits a bug report on page `report_bug`, a new issue is created automatically, immediately.
Users are not informed anywhere that these reports are made public as soon as they are created, and might assume that only system administrators will be able to see it and therefore might include personal information. I'm also not sure if organizations using this software have consent from their respective users to publicly disclose the bug with the name of the reporter.

I think this feature should be removed. If a user is capable of submitting a github issue, we could give them a link to this repo. Otherwise, it is much easier to get the report on a more interactive platform (like e-mail), and ask for additional information.

**Comment by kdmnk** [comment]
People won’t register to GitHub just to submit a small bug. It should be enough to inform them about publicity before they send the form or alternatively offer the email option.
