### ISSUE TITLE
Print via API

### ISSUE THREAD

**Issue by horcsinbalint** [EotvosCollegium/mars#445]
There has been a request that we should allow users to make prints automatically without human intervention for use with external automation.
One of my ideas was to make it possible for users to create API tokens which allows them to send a POST request to an API endpoint with their document.
We could start developing an API for mars but I think using a full-stack framework with allowing API requests would be a bit cumbersome (developing endpoints for both API requests and both for human users would be a bit tedious).

**Comment by kdmnk** [comment]
If they don't want to use our user interface you should allow them to somehow connect to the printer directly. It has all the api and configuration options one might need, there's no point in developing and maintaining this in Mars just to act as a middle man. 

Or I don't understand the needs.

**Comment by kdmnk** [comment]
If you want, It's fine to handle the tokens with Mars but I would not implement the communication through this system.

**Comment by horcsinbalint** [comment]
> If they don't want to use our user interface you should allow them to somehow connect to the printer directly. It has all the api and configuration options one might need, there's no point in developing and maintaining this in Mars just to act as a middle man.

One can only access the printer physically or the network traffic needs to go through our protected management network. (Or anybody would be able to communicate directly with the printer, which could be dangerous if someone on the internet plants malicious firmware on it.) Due to recent regulatory changes, we are unable to give access to the protected management network to non system administrators.

Mars has a way of keeping track of printing credits and giving out direct access to the printer would circumvent it.

> If you want, It's fine to handle the tokens with Mars but I would not implement the communication through this system.

Would you recommend us creating a different project which can be used with APIs?

**Comment by horcsinbalint** [comment]
After careful consideration, we have decided not to build a proper API but rather work on such issues on a per-user basis.
