### ISSUE TITLE
Free pages double sided printing

### ISSUE THREAD

**Issue by sszajbely** [EotvosCollegium/mars#51]
If you have 12 pages you should be able to print a 24 page long document if you choose to use double sided printing. Right it does not work.

**Comment by kdmnk** [comment]
Similar issue without free pages too. We experienced double sided printing which resulted only in the first two page printed double sided. Maybe it is an error with the printer.

**Comment by kdmnk** [comment]
@AdamSulan @viktorcsimma Could you test these sometime and identify any issues related to printing? (incl. balance changes)

**Comment by viktorcsimma** [comment]
@kdmnk I'll check it out now. Should I open new issues for them or list them here?

**Comment by kdmnk** [comment]
@viktorcsimma  We can collect the issues at #159. If you can, feel free to edit my post and add more checkboxes.
