### ISSUE TITLE
print/account_history endpoint does not give results in a reasonable timeframe

### ISSUE THREAD

**Issue by horcsinbalint** [EotvosCollegium/mars#536]
Requests coming to the `print/account_history` endpoint are answered extremely slowly. With the amount of data that we need to store, it exceeds the time limit for the given operation. We don't store that much data where it should be a problem.
I suspect that there is a problem in `PrintController::listPrintAccount()` (https://github.com/EotvosCollegium/mars/blob/7e9039bf34bc4f995a2bff76e4600a3252dcea37/app/Http/Controllers/Dormitory/PrintController.php#L226C1-L241C6):
```php
public function listPrintAccountHistory()
{
    $this->authorize('viewAny', PrintJob::class);

    $columns = ['user.name', 'balance_change', 'free_page_change', 'deadline_change', 'modifier.name', 'modified_at'];
    $paginator = TabulatorPaginator::from(
        PrintAccountHistory::join('users as user', 'user.id', '=', 'user_id')
            ->join('users as modifier', 'modifier.id', '=', 'modified_by')
            ->select('print_account_history.*')
            ->with('user')
            ->with('modifier')
    )->sortable($columns)
        ->filterable($columns)
        ->paginate();
    return $paginator;
}
```
I suspect that `with` statements cause a lot of additional queries and could be minimized to something like this:
```php
PrintAccountHistory::join('users as user', 'user.id', '=', 'user_id')
    ->join('users as modifier', 'modifier.id', '=', 'modified_by')
    ->select('user.name', 'print_account_history.balance_change', 'print_account_history.free_page_change', 'print_account_history.deadline_change', 'modifier.name', 'print_account_history.modified_at')
```
I haven't had enough time to examine it yet.

It could also be an operational problem, as it was observed after some regular maintenance.

**Comment by kdmnk** [comment]
Strange, as we paginate the data and only return x each time. But true that the with() calls can be optimised.

**Comment by horcsinbalint** [comment]
I think the problem was in fact with the `with()` statements as after #541 , the staging system seems to be responsive. We should check other parts of the codebase for this issue as I think this is quite common.

**Comment by horcsinbalint** [comment]
It was a problem with the database instance itself
