### ISSUE TITLE
Support exporting not just finished applicants' data

### ISSUE THREAD

**Issue by BertalanD** [EotvosCollegium/mars#592]
Currently `/admission/export` always uses the same filter: whether the application is finished:

https://github.com/EotvosCollegium/mars/blob/1c5f21b3bc9eeede160f132bfd27f0f86660b59b/app/Http/Controllers/Auth/AdmissionController.php#L216-L229

It would make sense to obey the filters set on the web interface. A pretty important use case is to export the email addresses of people with unfinished applications in order to send them a notification email prior to the deadline (there won't be an extension this year!)

**Comment by kdmnk** [comment]
We can send automatic reminders before the deadline with the PeriodicEvent's callbacks. Would we prefer that or this fix?

**Comment by BertalanD** [comment]
> We can send automatic reminders [...]

That also sounds good to me, although I'd prefer if it was manually activated (so that we don't actually trigger it from the staging instance, etc.).

But being able to give the student Committee/the Secretariat a list of email addresses would be good to have regardless.

**Comment by BertalanD** [comment]
Fixed by #626
