### ISSUE TITLE
Adding instructions for those with neither an application nor a tenant role

### ISSUE THREAD

**Issue by viktorcsimma** [EotvosCollegium/mars#603]
There have been some who have had an account but currently have no tenant status. For them, the instructions do not show up, because those are displayed only to those who have a tenant status but with a `tenant_until` field in the past.

There, we could display two options: one to request tenant status again and one which redirects to the application form. WDYT?

**Comment by kdmnk** [comment]
Can you test registering as tenant and check the gotten roles?

**Comment by viktorcsimma** [comment]
Hm... they do get a tenant role, with `tenant_until` set to the appropriate date.

But you are right the approach itself is flawed; I'll close this as per #604. See #609 for the new issue.
