### ISSUE TITLE
Finalise applications without profile picture

### ISSUE THREAD

**Issue by kdmnk** [EotvosCollegium/mars#611]
We have a finalised applicant without a profile picture which should not have been allowed.
Can someone investgate and fix quickly?

**Comment by BertalanD** [comment]
Making the profile picture optional was an explicit request from the Student Council.

(the reasoning being that this was pointed out as a potential problem while reviewing the Privacy Policy).

This change was made in https://github.com/EotvosCollegium/mars/commit/6496bb3dff590f69bf20ede37a036ca0bfdfbcc0
