### ISSUE TITLE
Finalize application form

### ISSUE THREAD

**Issue by kdmnk** [EotvosCollegium/mars#96]
Issues regarding the applications:

- [ ] Export function (similarly to the existing user export)
- [x] Option to change the status properly (at least banished -> finalized). Or, we might restructure this: finalized bool, called in bool, and accepted bool.
- [x] Approve the accepted applicants (with possibly an email notification as well), and at the same time, delete the user data of the disapproved ones
- [x] sort the names alphabetically
- [x] @machiato32 anything else?

**Comment by sszajbely** [comment]
- [x] Button to delete everything regarding applications (application forms as well as permissions to view them)
- [ ] Use livewire with the finalized/called in/accepted switch
- [x] Add a filter to the user manager for the year of acceptance (this is loosely related to the application form)
- [ ] Button for sending an email to the applicant to upload a non american style CV (if we see that they did upload an american style CV)
- [x] Add internet access to applicants with called in status

 I like the finalized, called in, accepted thing

**Comment by kdmnk** [comment]
I won't bother with the American CV thing. You can get their email address if you want to send an email like this.
